version: '3'

services:

  shop_apache:
    build: container/apache_php7/.
    hostname: ${DOMAIN}
    depends_on:
      - shop_mysql
    volumes:
      - ./data/www/:/var/www/html/:cached
    environment:
      DOMAIN: ${DOMAIN}
      APACHE_PORT: ${APACHE_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${APACHE_PORT}:80
      - ${APACHE_HTTPS_PORT}:443
    links:
      - shop_mailhog:mail.server
      
  shop_mysql:
    image: mysql:5.7
    hostname: mysql.${DOMAIN}
    volumes:
      - ./data/mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  shop_mailhog:
    hostname: mailhog.${DOMAIN}
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025

  shop_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: shop_mysql
